apiVersion: v1
kind: Service
metadata:
  name: hw3-backend
  labels:
    name: hw3-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: hw3-backend
  type: LoadBalancer