apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: swe645hw3_backend
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: swe645hw3_backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: swe645hw3-backend
          image: "yashreddym/swe645hw3_backend:latest"
          ports:
            - name: http
              containerPort: 8080