apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw3-backend
spec:
  selector:
    matchLabels:
      app: hw3-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: hw3-backend
    spec:
      containers:
        - name: hw3-backend
          image: 'gcr.io/my-project-1488083585442/hw3_backend'
          ports:
            - containerPort: 8080
