apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw3-frontend
spec:
  selector:
    matchLabels:
      app: hw3-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: hw3-frontend
    spec:
      containers:
        - name: hw3-frontend
          image: 'gcr.io/my-project-1488083585442/hw3_frontend'
          ports:
            - containerPort: 4200
