apiVersion: v1
kind: Service
metadata:
  name: hw3-frontend
  labels:
    name: hw3-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: hw3-frontend
  type: LoadBalancer